Prevent downloading over the current executable
alda-lang/alda-client-java pull request #25
Opened 2017-06-15 04:02 UTC by jgkamat

This approach creates a temp dir, moves the current executable to the
tmp dir, and download in place. If anything fails, we attempt to copy
the old executable back.

Hopefully eventually will close #24 (if tested/merged)

WIP (not tested), so don't merge yet!

2017-06-17 11:54 UTC, daveyarwood requested changes
Code looks good overall!

I can build you an `alda` and `alda.exe` with the changes from this PR and the version set to 1.0.0-rc10 so you can test updating. Will attach those shortly.

2017-06-17 11:54 UTC, daveyarwood commented on src/alda/AldaClient.java
> +      return;
Should maybe print a useful error message here before exiting

2017-06-17 11:54 UTC, daveyarwood commented on src/alda/AldaClient.java
> +        System.err.println("You will probably need to reinstall alda completely.");
Can we change this message to:

```
Please download the latest release of Alda from: https://github.com/alda-lang/alda/releases
```

2017-06-17 11:54 UTC, daveyarwood commented on src/alda/AldaClient.java
> +      return;
Oh -- reading the code more, it looks like `Util.moveFile` will already do that if it fails. 👍

2017-06-17 12:04 UTC, daveyarwood commented
Fake alda 1.0.0-rc10 that uses this branch of the client:
https://dl.dropboxusercontent.com/u/100360569/alda
https://dl.dropboxusercontent.com/u/100360569/alda.exe

2017-06-17 15:42 UTC, jgkamat commented
@daveyarwood unfortunately stack overflow lied to me, when a processs is running (in windows 10), I'm unable to even rename it when it's running:
```
C:\Users\jgkamat\Downloads>mv alda.exe alda.exe2
mv: cannot move 'alda.exe' to 'alda.exe2': Device or resource busy
```
I get this on both windows 7 and windows 10 unfortunately. I'm thinking the process can't rename its own file because of some weirdness in java/launch4j.

At this point, I think the best option to try (for windows only) is to use the [JNI](https://github.com/java-native-access/jna) library to call windows functions to do a file move on shutdown, and tell the user to reboot their machine. [See Kernel32->MoveFileEx](http://java-native-access.github.io/jna/4.4.0/javadoc/). (using the `MOVEFILE_DELAY_UNTIL_REBOOT` flag). Does that sound like a good idea to you (or do you know any way to use the `MOVEFILE_DELAY_UNTIL_REBOOT` move flag in java other than this?).

2017-06-17 15:57 UTC, jgkamat commented
Another thing we could do is make a seperate 'updater' program, which is downloaded and run by the alda executable, sort of like how minecraft does it (with it's launcher). I don't like this option because it seems pretty overkill for our needs though.

2017-06-17 16:26 UTC, jgkamat commented
Also, IRC logs of me asking for help, FWIW. 
```
09:04:30  jgkamat     Hey, I have a pretty complicated question, is it possible for a program to either (a: overwrite iself) or (b: move it's own binary) in windows? on linux/mac I can do both of these just fine, but I can't seem to do either of these in windows. I'm trying to make an app with a self-updater, FWIW.
09:05:14  HSKW (IRC)  DoYouKnow: i'm here
09:05:15  jgkamat     on the cli I get `device or resource busy` when moving my binary (when it's running).
09:05:22  ex4n1m0 (IRC)Use F8 or Shift + F8 (doesn't work when using UEFI BIOS & SSDs)
09:05:30  ex4n1m0 (IRC)try Shift F8
09:05:34  HSKW (IRC)  ex4n1m0: ok wait
09:08:19  weq (IRC)   jgkamat: not possible on windows.
09:08:51  HSKW (IRC)  ex4n1m0: Nothing, not work with Shift F8 :( i've SSD
09:09:08  wsky (IRC)  weq, actually it is possible on unpatched widnows
09:09:16  wsky (IRC)  weq, there were hackers that abused that
09:09:36  weq (IRC)   I don't think he was talking about that specially old scenario
09:09:37  jgkamat     I'm trying to target users though xD
09:10:06  HSKW (IRC)  ex4n1m0: disabled Uefi to Legacy i'm entered on windows 10 menu restore
09:10:24  jgkamat     weq: any way to work around it though? I guess I could make a seperate updater/launcher program but that seems like a lot of work....
09:10:35  weq (IRC)   jgkamat: the norm is either to use an updater app or instruct the os to replace upon boot. You can instruct it to replace on restart.
09:10:44  weq (IRC)   https://www.codeproject.com/Questions/621666/Download-and-replace-running-EXE
09:11:13  weq (IRC)   #winapi might have better input than mine
09:12:05  jgkamat     weq: Yah, another problem is that this is a java app :P. I think I found a way to call the replace on reboot thing with JNA though (https://github.com/java-native-access/jna)
09:12:15  jgkamat     thanks for the help though, :D
```

So according to them, we need to either make a seperate updater application (which we could call `alda-updater.exe` (which would add complexity and more windows-specific code), or we can use the move on reboot option (but that would force our users to reboot on updates). Let me know what you think :cry:

2017-06-17 17:10 UTC, daveyarwood commented
Hmm... I'd like to avoid going the JNA/JNI route, things tend to get
complex. I also don't like the idea of requiring users to reboot.

I think what I'd like to do is move toward a system where Alda is composed
of several programs, managed by a simple wrapper CLI program that will
become the "alda" executable. This program would know about the versions of
alda-client and alda-server that are installed and check for / install
updates. It could also serve as a proxy for the alda-client program: if the
command being run isn't "update," it could simply run the alda-client
program and pass through the command line arguments.

What do you think of that idea?

One wrinkle is that we might occasionally need to update the wrapper
program, in which case Windows users would have to manually replace the
executable. But, I think we could recognize that rare case and print out
the commands for the user to run.

On Jun 17, 2017 12:26 PM, "Jay Kamat" <notifications@github.com> wrote:

> Also, IRC logs of me asking for help, FWIW.
>
> 09:04:30  jgkamat     Hey, I have a pretty complicated question, is it possible for a program to either (a: overwrite iself) or (b: move it's own binary) in windows? on linux/mac I can do both of these just fine, but I can't seem to do either of these in windows. I'm trying to make an app with a self-updater, FWIW.
> 09:05:14  HSKW (IRC)  DoYouKnow: i'm here
> 09:05:15  jgkamat     on the cli I get `device or resource busy` when moving my binary (when it's running).
> 09:05:22  ex4n1m0 (IRC)Use F8 or Shift + F8 (doesn't work when using UEFI BIOS & SSDs)
> 09:05:30  ex4n1m0 (IRC)try Shift F8
> 09:05:34  HSKW (IRC)  ex4n1m0: ok wait
> 09:08:19  weq (IRC)   jgkamat: not possible on windows.
> 09:08:51  HSKW (IRC)  ex4n1m0: Nothing, not work with Shift F8 :( i've SSD
> 09:09:08  wsky (IRC)  weq, actually it is possible on unpatched widnows
> 09:09:16  wsky (IRC)  weq, there were hackers that abused that
> 09:09:36  weq (IRC)   I don't think he was talking about that specially old scenario
> 09:09:37  jgkamat     I'm trying to target users though xD
> 09:10:06  HSKW (IRC)  ex4n1m0: disabled Uefi to Legacy i'm entered on windows 10 menu restore
> 09:10:24  jgkamat     weq: any way to work around it though? I guess I could make a seperate updater/launcher program but that seems like a lot of work....
> 09:10:35  weq (IRC)   jgkamat: the norm is either to use an updater app or instruct the os to replace upon boot. You can instruct it to replace on restart.
> 09:10:44  weq (IRC)   https://www.codeproject.com/Questions/621666/Download-and-replace-running-EXE
> 09:11:13  weq (IRC)   #winapi might have better input than mine
> 09:12:05  jgkamat     weq: Yah, another problem is that this is a java app :P. I think I found a way to call the replace on reboot thing with JNA though (https://github.com/java-native-access/jna)
> 09:12:15  jgkamat     thanks for the help though, :D
>
> So according to them, we need to either make a seperate updater
> application (which we could call alda-updater.exe (which would add
> complexity and more windows-specific code), or we can use the move on
> reboot option (but that would force our users to reboot on updates). Let me
> know what you think 😢
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/alda-lang/alda-client-java/pull/25#issuecomment-309225029>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEroF9t9ywAq85LjXA62MTvyofHLppFXks5sE_4egaJpZM4N6tLJ>
> .
>

2017-06-18 06:45 UTC, jgkamat commented
I don't like the idea of a seperate server/client binary (at least right now) for a couple reasons

1) it would make installs more complex, if the `alda` wrapper breaks for any reason, you would have to copy two binaries over manually
2) (as you said) it would make updating the wrapper a huge pain.
3) linux/mac users (if we used the same behavior on both platforms) would need to suddenly run the updater as root since the binary isn't replacing itself, but other programs. (This is actually true in this PR too, because it's moving files onto the path).
4) The upgrade path for existing users might be a little complicated (we would need to think this out carefully).
5) It would make new releases harder to create (for you), and harder to understand (for end users) since there will be 3 binaries to choose from (across 2 platforms, making 6 total).

I've been thinking about this problem for a while, and I think I've come up with a solution which I like (at least, the best solution I could think of).

1) Keep the update mechanics for linux/mac exactly the same as right now. This will prevent existing users from having to run the application as root.
2) On windows, `alda update` will download the new alda release to a temporary directory (instead of over itself), and then execute something like `alda update --copy-to /path/to/running/alda.exe` _on the freshly downloaded version_, and quit.
3) The new process will wait until the `alda.exe` process has quit, and copy itself over the `alda.exe` on the path (which would need admin privileges). If `alda.exe` doesn't quit, warn the user and do nothing.

I like this method since it keeps packaging exactly the same as right now, and is fairly simple to implement. It also removes the need for a seperate wrapper program.

I do like the idea of having multiple binaries, but I don't think we're at a stage where we could pull that offf well. Git does this very well, but that's because git installs are managed by a package manager (on linux/mac), and on windows, everything is managed by a GUI installer. Right now there's no stable version of alda, which means it's probably not going to get into package managers any time soon. Once we have a stable release, we should look into getting alda packaged for multiple distros, making a gui installer for windows and (eventually) deprecating the alda updater.

Let me know what you think though, this is something that we probably want to get right right now, so we don't have to worry about it later :smile:

2017-06-18 15:06 UTC, daveyarwood commented
I have to run at the moment -- will think more about this in detail, but one quick thing:

> 3) linux/mac users (if we used the same behavior on both platforms) would need to suddenly run the updater as root since the binary isn't replacing itself, but other programs. (This is actually true in this PR too, because it's moving files onto the path).

I'm not sure that that's necessarily true. I wrote a little Java program to demo overwriting another program while it's running: https://github.com/daveyarwood/program-replacer

I haven't had time to test in my Ubuntu VM, but at least on my OS X host, I am able to replace the contents of another program in `/usr/local/bin` while it's running, and without needing to be root.

2017-06-18 17:54 UTC, jgkamat commented
No problem, there's no rush! :smile: 

I think I might have made it a little unclear what I meant about `(3)` (and I was a little confued before too). On linux systems, the directory `/usr/local/bin` is owned by root, which means creating new files in that directory is not allowed without root permissions:

For example, here's the permission (via `ls -ld`) of a couple of directories on my path:

```
drwxr-xr-x 2 root root 4096 Jun  4 11:57 /usr/local/bin
drwxr-xr-x 2 root root 4096 Jun  5 23:03 /bin
drwxr-xr-x 2 root root 4096 Dec 18 08:31 /usr/local/sbin
drwxr-xr-x 2 root root 4096 Jun  2 23:14 /sbin
```

However, most users download alda themselves, and then run:
`sudo mv ~/Downloads/alda /usr/local/bin/alda`

Running this command without sudo will not work, since `/usr/local/bin` is owned by root. However, the _file itself_ is owned by the user (in this case `jay`), since I'm the one who initially created the file, leading to this:

```
drwxr-xr-x 2 root root 4096 Jun 18 10:38 /usr/local/bin/
-rwxr-xr-x 1 jay jay 7424671 Jun 18 10:37 /usr/local/bin/alda
```

This means that I have permission to run,execute, and even write to `/usr/local/bin/alda` but I don't have permission to rename it or create new directories/files in `/usr/local/bin`. In unix systems, it shouldn't matter whether a program is running or not when you overwrite it (that's how all the package managers work).

```
[jay@laythe program-replacer]$ mv /usr/local/bin/alda /usr/local/bin/alda2                                                                                                                                          [master↓] [52315] 10:42AM
mv: cannot move '/usr/local/bin/alda' to '/usr/local/bin/alda2': Permission denied
[jay@laythe program-replacer]$ rm /usr/local/bin/alda                                                                                                                                                               [master↓] [52316] 10:42AM
rm: cannot remove '/usr/local/bin/alda': Permission denied
[jay@laythe program-replacer]$ echo "hello world" > /usr/local/bin/alda                                                                                                                                             [master↓] [52317] 10:42AM
[jay@laythe program-replacer]$ cat /usr/local/bin/alda                                                                                                                                                              [master↓] [52318] 10:42AM
hello world
```

This means we can run the alda updater as root (since the `jay` user, what `alda` is running as, has permissions to write over the `alda` binary. If I decide to change the ownership of the alda binary itself to root, the updater fails (unless I run it as root):


```
[jay@laythe Downloads]$ alda update                                                                                                                                                                                           [52326] 10:44AM
Install alda '1.0.0-rc60' over '1.0.0-rc59' ? [yN]: y
Downloading https://github.com/alda-lang/alda/releases/download/1.0.0-rc60/alda...
An error occured while downloading a file (2).
java.io.FileNotFoundException: /usr/local/bin/alda (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at alda.Util.downloadFile(Util.java:190)
	at alda.AldaClient.updateAlda(AldaClient.java:87)
	at alda.Main.main(Main.java:222)

Updated alda 1.0.0-rc59 => 1.0.0-rc60.
If you have any currently running servers, you may want to restart them so that they are running the latest version.
``` 

(the error handling was completely wrong before, sorry about that :P)

This means if I run the program replacer once without having any binary present I get this error:

```
[jay@laythe program-replacer]$ java -jar target/replacer.jar                                                                                                                                                        [master↓] [52225] 10:07AM
Replacing /usr/local/bin/replaceme1234567890...
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/local/bin/replaceme1234567890
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3351)
	at java.nio.file.Files.write(Files.java:3397)
	at replacer.Main.main(Main.java:39)
```

But if I create a file owned by me with the same name, everything works fine.

If we transitioned to this new model, we would need the user to download and copy over every file to `/usr/local/bin`, since the updater could not create any new files (without root). If someone ran the updater as root (so the updater could handle downloading all the files), the new files would be created as root, which means you would need root to update them later on. 

Also, I wanted to add one more reason I don't like the multiple files idea: It would make running old versions a little harder (since people would need to copy over 3 files instead of just one, if they just installed the wrapper, they would get the latest version). 

Let me know what you think! :smile:

2017-06-19 03:29 UTC, daveyarwood commented
OK, that makes perfect sense. But with that in mind, I will make one more lengthy argument for multiple executables... (please bear with me, ultimately I don't want to do this yet) 😄 

What if we kept all of the executables in a directory like `~/.alda/bin`? The setup process could be this:

1. Download `alda` (the updater/installer/wrapper program) from GitHub and place it in `~/.alda/bin`.

1. Add `~/.alda/bin` to your `$PATH`.

1. Run `alda update`. This would check for the latest versions of the server and client and download them into `~/.alda/bin`.

We could provide an install script to automate this, or better yet, add Alda to package managers like Homebrew and APT.

One could argue that having `alda update` update 2 (or 3, if you count `alda` itself) programs would make it difficult to troubleshoot user issues because the user might have any combination of versions of the server and client installed. And that's a fair point. But I think that if we do this right, there will be little chance of running into issues because of that.

  - We can make `alda update` an atomic operation -- e.g. if both the server and the client have updates available, but one of them fails to download, we abort entirely and keep things as they were before attempting to update. (If we want to be extra safe, we can compare the shasums of downloaded files to ensure they haven't been corrupted or partially downloaded.)

  - We can be extra diligent about not shipping changes that aren't backwards compatible. For example, if we want to add a new feature to the client that requires a server change, we would be sure to deploy the new server version first.

  - We can have `alda version` spit out the version of each executable. When reporting issues, users could provide this output so that we can reproduce their setup. I realize this is more complicated than just downloading a prior version of Alda as a single file, but I don't think it's totally unreasonable. I would also argue that we don't need to support previous versions of Alda (or specific combinations of previous versions of the client and server) -- we can always ask that people try running `alda update` and see if that fixes the issue.

I know this all sounds like I'm going to a lot of trouble to recommend doing things in a more complicated way, but to me, the potential benefits are:

- Smaller, more lightweight processes: the server would only need to contain server code, and the client would only need to contain client code.

- The door would be open for us to experiment with rewriting components in different languages or for different runtimes. I'm personally interested in experimenting with moving away from Clojure because of its slow start-up time and JVM performance issues. But I don't want to have to completely rewrite Alda in another language. We could potentially break up the Alda worker process into several smaller processes (e.g. parser, compiler, score-builder, performer) and start replacing smaller parts.

  This is all sort of a thought experiment right now... it could be sensible, or it could be completely insane. I'm not quite sure yet. 😁 

  I am at least pretty sure that replacing the performance part of Alda with something non-JVM would be a big win for performance reasons. I'm particularly interested in exploring the browser as a sound engine. The Web Audio API, when coupled with [MIDI.js](https://github.com/mudcube/MIDI.js/) can do everything the JVM can do and much more.

---

So, after having typed all that out and spent a good deal of time thinking about it, I think maybe it would be best if I did some experimenting with this on my own, and we can hold off on making any big changes to the way Alda is structured until I'm 100% sure that it's worthwhile. 

It's definitely nice to have a single executable, so maybe we should keep doing it this way for as long as we can. I think your workaround sounds like a good approach, and I like the idea of only following that code path if the OS is Windows, otherwise continue to use the current behavior.

2017-06-19 07:54 UTC, jgkamat commented
I actually really like this idea (moving the secondary binaries to `~/.alda/bin`)! It solves a lot of the issues that I had with the original structure. I do think we need to properly evaluate this and make sure everything will work before we deploy this out though. A few thoughts:

I don't think we need to make users add `~/.bin/alda` to their path, the `alda` wrapper could be placed in a location the user wants on the path, and the alda binary will then go ahead and make/download files to `~/.alda/bin`. When it executes it's commands it will search there manually, instead of searching all over the path

The `~/.alda/bin` location should be customizable for external packaging (and if it is customized, the updater should be disabled). This would make packaging easier (I think, at least). 

We would need to come up with a solid way for the auto-updater to upgrade itself. It could ask for root (if needed) on *nix, and (maybe) we could ask for a manual overwrite on windows.

We could probably learn a lot from the way git is structured/packaged. I think it's packaged in a very similar way to what we would like to acheive, and they've been doing that well for a while.

We need to come up with a good way to upgrade users from the existing structure with minimal impact to them (which is probably publishing the wrapper under the same old format as before). 

We probably should build a way to pin at a specific version (ie: `alda update 1.0.0-RC50`, for people who really want to downgrade for some reason).

If this is all done right, I think that (as you said) the benifits would make it worth it, but that's a big restructure, so I think I'm going to (try) and hack the workaround I thought up for windows above, and once we have this all ironed out and deployed (if we do it), we can delete that said workaround.

2017-06-19 12:05 UTC, daveyarwood commented
Lots of good ideas here! If you're onboard, I think I'll start making a bunch of small GitHub issues to organize the effort of moving to the new `~/.alda/bin` system.

It seems like we'll need a workaround for Windows users anyway whenever we want to update the updater, so it's worth doing now and keeping around.

As for Linux users not being able to write to `/usr/local/bin`, I think there are a few options:

- Run `sudo alda update` instead of `alda update`.
- `chown -R $USER /usr/local/bin` so that you own it 😄  
  (or maybe just `chown $USER /usr/local/bin/alda` would work?)
- Keep `alda` in a different folder on your `$PATH` that you own.
- We may not need to do anything: if you downloaded `alda` and moved it to `/usr/local/bin`, then  you already own it, and probably have permission to update it. And the other files would all be in `~/.alda/bin` which you own.

> We probably should build a way to pin at a specific version (ie: `alda update 1.0.0-RC50`, for people who really want to downgrade for some reason).

An open question I have about this is whether Alda as a whole should continue to have a version number. My gut feeling is "yes," as it would be more comfortable / less confusing for users to think of Alda's version that way, e.g. "I have Alda version 1.0.0 installed." vs. "`alda version` says I have alda-client version 0.3.1 and alda-server version 0.3.0."

Maybe what we need is some sort of registry (stored in the `alda-lang/alda` GitHub repo, perhaps?) that lists each version and what its dependency versions are. That would give us the ability to specify an overall version number for each release, as well as to keep updates atomic.

2017-06-19 15:16 UTC, daveyarwood commented
> We could probably learn a lot from the way git is structured/packaged. I think it's packaged in a very similar way to what we would like to acheive, and they've been doing that well for a while.

I'm curious to know more about how git works -- do you have some info on that?

2017-06-20 04:30 UTC, jgkamat commented
Now that I actually took a bit of time to explore around, git is packaged a lot differently than I thought. 

When you build git from source, it places a bunch of binaries in the target dir, there's one for every single command (`git-status`, `git-commit`, etc). Most of these binaries don't actually make it onto the path, but some do:
```
[jay@laythe git]$ ls /usr/bin/git*
/usr/bin/git  /usr/bin/git-clang-format  /usr/bin/git-credential-libsecret  /usr/bin/git-cvsserver  /usr/bin/git-receive-pack  /usr/bin/git-shell  /usr/bin/git-upload-archive  /usr/bin/git-upload-pack
```

I used to think that the `git` executable slaved off to these other ones, but it seems to work even when I delete all the `git-*` executables(?) 

Either way, git places multiple binaries on the path with the assistance of the package manager (something we will probably leverage). 

git dosen't have a internal updater though, so it doesen't have to deal with any of the updating problems we'll have to go through when we design this system.

2017-06-24 20:57 UTC, jgkamat commented
After a bunch of testing, I really am starting to dislike the method of updating that I proposed earlier.
(My current WIP is here: https://github.com/jgkamat/alda-client-java/tree/jay/broken-windows-updater).

I don't think that it would provide a satisfactory UX (and would lead to more broken installs than is worth). 

1. We would have to fork off into the background to call the copy script, which introduces the problem of not being able to report back status. We won't know if we succeded or failed, and the user has to find out manually
2. Because we have many processes running in the background (server, workers, etc), it's hard to make sure that everything has been stoppped before copying. This leads to a bunch of errors (which causes failed upgrades).

At this point, I think a better solution is to print out a command that the user can run to download over, and the user can deal with the commands as they want (run as admin, reboot and try again, etc). 

I think this is why every single windows app I know uses gui installers that tell you to reboot after they are completed :cry:...

I'm willing to keep working on it if you think this is a good idea though, what are your thoughts?

2017-06-26 01:58 UTC, daveyarwood commented
Yeah, I definitely see what you mean. It seems like from our perspective, Windows is a complicated environment to run Alda in, because a Windows application is expected to be a single program that runs in isolation and is expected not to go anywhere or be overwritten while it is running.

Meanwhile, in Unix-land, we are doing complicated things like running multiple processes that communicate with each other over TCP, and it's possible for Alda process A to be talking with Alda process B after process A has been upgraded to a newer version of itself.

I'm skeptical that it's worth the effort to try to make such complicated workflows "just work" in the same way when running Alda in a Windows environment. I think it's nice that we allow Alda to work in general on Windows, and I'd like to maintain that in the future (i.e. I at least want Windows users to be able to use Alda), but I also think it's fine if we occasionally require Windows users to take extra steps like you're describing, as a workaround for the limitations of the OS.

2017-07-07 06:00 UTC, jgkamat commented
Closing in favor of #28

2017-07-07 06:00 UTC, closed without merging